http:
  routers:
    app-router:
      # Replace with your production hostnames
      rule: Host(`yourdomain.tld`) || Host(`www.yourdomain.tld`)
      service: whoami-service
      entryPoints:
        - websecure
      tls:
        certResolver: letsencrypt

  services:
    whoami-service:
      loadBalancer:
        servers:
          - url: "http://whoami:80"
